function keys=ph_general_settings(project,keys)


%% general settings (multi-summary PSTH)
keys.plot                               =0;
keys.plot_waveforms                     =0;
keys.delete_previous_pdfs               =0;
keys.create_pdfs                        =1;
keys.append_pdfs                        =0;
keys.effectors_on_same_figure           =0; %% here to control displaying saccade windows in reaches in population 

keys.list_successful_only               =1;
keys.minimum_trials_per_condition       =60;
keys.min_n_spikes_per_unit              =50;
keys.process_only_units_in_the_table    =1; % sorting table
keys.MA_selection                       ={};
keys.PSTH_binwidth                      =0.01;
keys.contra_color                       ='pink';
%keys.MA_selection={'tar_range_x',[-30,30],'tar_range_y',[-1,30]};

keys.cal.stablity       =[0,1];
keys.cal.single_rating  =[1,2,3];

%% folders and filenames
keys.drive                  ='Y:';
keys.basepath_to_save       =['Archive\' project '\ephys'];
keys.pdf_folders            ={''};
spike_analysis_location     = which('ph_initiation');
keys.db_folder              =spike_analysis_location(1:strfind(spike_analysis_location,'ph_initiation')-1);

keys.Flaffus.sorted_neurons_filename    ='Fla_sorted_neurons';
keys.Linus.sorted_neurons_filename      ='Lin_sorted_neurons';
keys.Curius.sorted_neurons_filename     ='Cur_sorted_neurons';
keys.Tesla.sorted_neurons_filename      ='Tes_sorted_neurons';
keys.Cornelius.sorted_neurons_filename  ='Cor_sorted_neurons';

keys.Flaffus.filelist_formatted         ={};
keys.Linus.filelist_formatted           ={};
keys.Curius.filelist_formatted          ={};
keys.Tesla.filelist_formatted           ={};
keys.Cornelius.filelist_formatted       ={};
%% population PSTH settings

keys.combine_monkeys                    =1;

%    keys.population_normalization   = 'none';
    keys.pop                        = struct('epoch_RF',{''},'epoch_BL',{'INI'},'epoch_for_normalization',{''},'normalization',{'none'},'FR_subtract_baseline',{0},...
                                             'only_both_hands',{},'only_overlapping_tasktypes',{},'combine_tuning_properties',{{}},'group_parameter',{''},'group_excluded',{{'','-'}},'Selection',{{}},'unselect',{{}},...
                                             'conditions_to_plot',{{''}},'plot_RF',{0},'y_lim',{});

                                         
%% tuning table readout options (excluding particular subsets)

keys.tt.combine_tuning_properties   ={'place_name_here'}; %% additional table entry from combining columns
keys.tt.only_both_hands             =0; 
keys.cc.only_both_hands             =0; 
keys.tt.only_overlapping_tasktypes  =0;  % for both cell coutns AND population PSTH AND scatter (?)

keys.tt.epoch_criterion             ='none';
keys.tt.space_criterion             ='none';
keys.tt.hands_criterion             ='none';
keys.tt.SXH_criterion               ='none';
keys.tt.selection                   ={};
keys.tt.unselect                    ={};
                                         
%% Cell count epochs

keys.cc.conditions_to_plot  ={'Dcfr','Ddre','Ddsa'};
keys.cc.epochsE.Msac        ={'INI', 'Facq','Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';
keys.cc.epochsS.Msac        ={'Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';
keys.cc.epochsE.Vsac        ={'INI', 'Facq','Cue','PreS','PeriS','Tacq','Thol'}';
keys.cc.epochsS.Vsac        ={'Cue','PreS','PeriS','Tacq','Thol'}';
keys.cc.epochsE.Ddre        ={'INI', 'Facq','Fhol','Cue','Del','PreS','PeriS','PostS','PreR','PeriR','PostR','Thol'}';
keys.cc.epochsS.Ddre        ={'Cue','Del','PeriS','PeriR','Thol'}';
keys.cc.epochsE.Dcfr        ={'INI', 'Facq','Fhol','Cue','Del','PreS','PeriS','PostS','PreR','PeriR','PostR','Thol'}';
keys.cc.epochsS.Dcfr        ={'Cue','Del','PeriS','PeriR','Thol'}';
keys.cc.epochsE.Ddsa        ={'INI', 'Facq','Fhol','Cue','Del','PreS','PeriS','PostS','PreR','PeriR','PostR','Thol'}';
keys.cc.epochsS.Ddsa        ={'Cue','Del','PeriS','PeriR','Thol'}';

%% subregion keys..?
keys.Subregions_separately      =0;
keys.Subregions{1}{1}           =struct('monkey',{''},'target',{''},'grid_x',{NaN},'grid_y',{NaN},'z_min',{NaN},'z_max',{NaN});
keys.n_Subregions               =numel(keys.Subregions);

%% EPOCH SETTINGS %%
%% For each task type seperately, analysis epochs are defined
%% 

%% Direct type
keys.EPOCHS_PER_TYPE{1}={...
    'INI',      2,	-0.5,	0,      -0.4,	-0.1,   'INI';...
    'Facq',     3,	-0.4,   0.17,	0.05,	0.15,   'INI';...
    'Fhol',     4,	-0.33,	0,      -0.3,	0,      'INI';...
    'Ton',      4,	0,      0.12,	0.05,	0.12,   'INI';...
    'PreS',     60,	-0.1,   0,      -0.1,	-0.01,  'INI';...
    'PeriS',    60,	-0.01,	0.05,	-0.01,	0.05,   'INI';...
    'Tacq',     5,	-0.05,	0.17,	0,      0.15,   'INI';...
    'Thol',     20,	-0.33,	0.1,	-0.3,	0,      'INI';...
    };
keys.epoch_comparisons{1}={'INI' 'Facq';...
    'Facq' 'Fhol';...
    'Fhol' 'Ton';...
    'Fhol' 'PreS';...
    'Fhol' 'PeriS';...
    'Fhol' 'Tacq';...
    'Fhol' 'Thol'};

keys.epochs_for_multicomparison{1}          ={'INI','Facq','Fhol','Ton','PreS','PeriS','Tacq','Thol'}';
keys.epochs_spaceLR_multicomp{1}            ={'Ton','PreS','PeriS','Tacq','Thol'}';
keys.epochs_choice_multicomp{1}             ={'Ton','PreS','PeriS','Tacq','Thol'}';
keys.epochs_hands_multicomp{1}              ={'Facq','Fhol','Ton','PreS','PeriS','Tacq','Thol'}';
keys.epochs_SxH_multicomp{1}                ={'Ton','PreS','PeriS','Tacq','Thol'}';
keys.epochs_to_plot_PSTH{1}                 ={'INI','Facq','Fhol','Ton','PreS','PeriS','Tacq','Thol'}';

%% Direct type
keys.EPOCHS_PER_TYPE{2}={...
    'INI',      2,	-0.5,	0,      -0.4,	-0.1,   'INI';...
    'Facq',     3,	-0.4,   0.17,	0.05,	0.15,   'INI';...
    'Fhol',     4,	-0.33,	0,      -0.3,	0,      'INI';...
    'Cue',      4,	0,      0.17,	0.05,	0.12,   'INI';...
    'PreS',     60,	-0.1,   -0.01,  -0.1,	-0.01,  'INI';...
    'PeriS',    60,	-0.01,	0.22,	-0.01,	0.05,   'INI';...
    'PostS',	61,	0,      0.2,	0.05,   0.2,    'INI';...
    'PreR',     62,	-0.3,   0,      -0.3, 	-0.01,  'INI';...
    'PeriR',	62,	-0.35,  0.7,    -0.05, 	0.15,   'INI';...
    'PostR',	63,	0,      0.2,	0.05,   0.2,    'INI';...
    'Tacq',     5,	0,      0.2,	0,      0.15,   'INI';...
    'Thol',     20,	-0.3,	0.1,	-0.3,	0,      'INI';...
    };
keys.epoch_comparisons{2}={'INI' 'Facq';...
    'Facq' 'Fhol';...
    'Fhol' 'Cue';...
    'Fhol' 'PreS';...
    'Fhol' 'PeriS';...
    'Fhol' 'PostS';...
    'Fhol' 'PreR';...
    'Fhol' 'PeriR';...
    'Fhol' 'PostR';...
    'Fhol' 'Tacq';...
    'Fhol' 'Thol'};

keys.epochs_for_multicomparison{2}          ={'INI','Facq','Fhol','Cue','PreS','PeriS','PostS','PreR','PeriR','PostR','Tacq','Thol'}';
keys.epochs_spaceLR_multicomp{2}            ={'Cue','PreS','PeriS','PostS','PreR','PeriR','PostR','Tacq','Thol'}';
keys.epochs_choice_multicomp{2}             ={'Cue','PreS','PeriS','PostS','PreR','PeriR','PostR','Tacq','Thol'}';
keys.epochs_hands_multicomp{2}              ={'Facq','Fhol','Cue','PreS','PeriS','PostS','PreR','PeriR','PostR','Tacq','Thol'}';
keys.epochs_SxH_multicomp{2}                ={'Cue','PreS','PeriS','PostS','PreR','PeriR','PostR','Tacq','Thol'}';
keys.epochs_to_plot_PSTH{2}                 ={'INI','Facq','Fhol','Cue','PeriS','PostS','PreR','PeriR','PostR','Thol'}';

%% Memory type
keys.EPOCHS_PER_TYPE{3}={...
    'INI',      2,	-0.5,	0,      -0.4,	-0.1,   'INI';...
    'Facq',     3,	-0.4,   0.17,	0.05,	0.15,   'INI';...
    'Fhol',     6,	-0.33,	0,      -0.3,	0,      'INI';...
    'Cue',      6,	0,      0.28, 	0.05,   0.15,   'INI';...
    'MemE',     7, 	0,      0.5,    0,      0.2,    'INI';...
    'MemL',     9,	-0.5,   0,      -0.3, 	0,      'INI';...
    'PreS',     60,	-0.2,   0,      -0.1, 	-0.01,  'INI';...
    'PeriS',	60,	-0.1,   0.05,	-0.01, 	0.05,   'INI';...
    'TIhol',	10,	0,      0.2,    0,      0.1,    'INI';...
    'Thol',     20,	-0.5,   0,      -0.3,   0,      'INI';...
    };

keys.epoch_comparisons{3}={'INI' 'Facq';...
    'Facq' 'Fhol';...
    'Fhol' 'Cue';...
    'Fhol' 'MemE';...
    'Fhol' 'MemL';...
    'Fhol' 'PreS';...
    'Fhol' 'PeriS';...
    'Thol' 'TIhol';...
    'Fhol' 'Thol';...
    };

keys.epochs_for_multicomparison{3}          ={'INI','Facq','Fhol','Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';
keys.epochs_spaceLR_multicomp{3}            ={'Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';
keys.epochs_choice_multicomp{3}             ={'Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';
keys.epochs_hands_multicomp{3}              ={'Facq','Fhol','Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';
keys.epochs_SxH_multicomp{3}                ={'Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';
keys.epochs_to_plot_PSTH{3}                 ={'INI','Facq','Fhol','Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';

%% Delay type
keys.EPOCHS_PER_TYPE{4}={...
    'INI',      2,	-0.5,	0.4,    -0.4,	-0.1,   'INI';...
    'Facq',     3,	-1.2,   0.17,	-0.4,	-0.1,   'INI';...
    'Fhol',     6,	-0.33,	0,      -0.3,	0,      'INI';...
    'Cue',      6,	-0.33,  1.35, 	0.05,   0.15,   'INI';...
    'EDel',     4, 	-0.6,   -0.3,   -0.6,   -0.3,   'INI';...
    'Del',      4, 	-0.3,   0,      -0.3,   0,      'INI';...
    'PreS',     60,	-0.2,   0,      -0.1, 	-0.01,  'INI';...
    'PeriS',	60,	-0.1,   0.6,	-0.01, 	0.05,   'INI';...
    'PostS',	61,	0,      0.2,	0.05,   0.2,    'INI';...
    'PreR',     62,	-0.3,   0,      -0.3, 	-0.01,  'INI';...
    'PeriR',	62,	-0.35,  0.7,    -0.05, 	0.15,   'INI';...
    'PostR',	63,	0,      0.2,	0.05,   0.2,    'INI';...
    'Thol',     20,	-0.3,   0,      -0.3,   0,      'INI';...
    };

keys.epoch_comparisons{4}={'INI' 'Facq';...
    'INI' 'Fhol';...
    'Fhol' 'Cue';...
    'Fhol' 'EDel';...
    'EDel' 'Del';...
    'EDel' 'PreS';...
    'EDel' 'PeriS';...
    'EDel' 'PostS';...
    'EDel' 'PreR';...
    'EDel' 'PeriR';...
    'EDel' 'PostR';...
    'Fhol' 'Thol';...
    };

keys.epochs_for_multicomparison{4}          ={'INI','Facq','Fhol','Cue','EDel','Del','PreS','PeriS','PostS','PreR','PeriR','PostR','Thol'}';
keys.epochs_spaceLR_multicomp{4}            ={'INI','Facq','Fhol','Cue','EDel','Del','PreS','PeriS','PostS','PreR','PeriR','PostR','Thol'}';
keys.epochs_choice_multicomp{4}             ={'INI','Facq','Fhol','Cue','EDel','Del','PreS','PeriS','PostS','PreR','PeriR','PostR','Thol'}';
keys.epochs_hands_multicomp{4}              ={'INI','Facq','Fhol','Cue','EDel','Del','PreS','PeriS','PostS','PreR','PeriR','PostR','Thol'}';
keys.epochs_SxH_multicomp{4}                ={'INI','Facq','Fhol','Cue','EDel','Del','PreS','PeriS','PostS','PreR','PeriR','PostR','Thol'}';
keys.epochs_to_plot_PSTH{4}                 ={'INI','Facq','Fhol','Cue','EDel','Del','PreS','PeriS','PostS','PreR','PeriR','PostR','Thol'}';

%% M2S

keys.EPOCHS_PER_TYPE{5}={...
    'INI',      2,	-0.5,	0,      -0.4,	-0.1,   'INI';...
    'Facq',     3,	-0.4,   0.17,	0.05,	0.15,   'INI';...
    'Fhol',     6,	-0.33,	0,      -0.3,	0,      'INI';...
    'Cue',      6,	0,      0.28, 	0.05,   0.15,   'INI';...
    'MemE',     7, 	0,      0.5,    0,      0.2,    'INI';...
    'MemL',     9,	-0.5,   0,      -0.3, 	0,      'INI';...
    'PreS',     60,	-0.2,   0,      -0.1, 	-0.01,  'INI';...
    'PeriS',	60,	-0.1,   0.05,	-0.01, 	0.05,   'INI';...
    'TIhol',	10,	0,      0.2,    0,      0.1,    'INI';...
    'Thol',     20,	-0.5,   0,      -0.3,   0,      'INI';...
    };

keys.epoch_comparisons{5}={'INI' 'Facq';...
    'Facq' 'Fhol';...
    'Fhol' 'Cue';...
    'Fhol' 'MemE';...
    'Fhol' 'MemL';...
    'Fhol' 'PreS';...
    'Fhol' 'PeriS';...
    'Thol' 'TIhol';...
    'Fhol' 'Thol';...
    };

keys.epochs_for_multicomparison{5}          ={'INI','Facq','Fhol','Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';
keys.epochs_spaceLR_multicomp{5}            ={'Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';
keys.epochs_choice_multicomp{5}             ={'Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';
keys.epochs_hands_multicomp{5}              ={'Facq','Fhol','Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';
keys.epochs_SxH_multicomp{5}                ={'Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';
keys.epochs_to_plot_PSTH{5}                 ={'INI','Facq','Fhol','Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';

%% M2S

keys.EPOCHS_PER_TYPE{6}={...
    'INI',      2,	-0.5,	0,      -0.4,	-0.1,   'INI';...
    'Facq',     3,	-0.4,   0.17,	0.05,	0.15,   'INI';...
    'Fhol',     6,	-0.33,	0,      -0.3,	0,      'INI';...
    'Cue',      6,	0,      0.28, 	0.05,   0.15,   'INI';...
    'MemE',     7, 	0,      0.5,    0,      0.2,    'INI';...
    'MemL',     9,	-0.5,   0,      -0.3, 	0,      'INI';...
    'PreS',     60,	-0.2,   0,      -0.1, 	-0.01,  'INI';...
    'PeriS',	60,	-0.1,   0.05,	-0.01, 	0.05,   'INI';...
    'TIhol',	10,	0,      0.2,    0,      0.1, 	'INI';...
    'Thol',     20,	-0.5,   0,      -0.3,   0,      'INI';...
    };

keys.epoch_comparisons{6}={'INI' 'Facq';...
    'Facq' 'Fhol';...
    'Fhol' 'Cue';...
    'Fhol' 'MemE';...
    'Fhol' 'MemL';...
    'Fhol' 'PreS';...
    'Fhol' 'PeriS';...
    'Thol' 'TIhol';...
    'Fhol' 'Thol';...
    };

keys.epochs_for_multicomparison{6}          ={'INI','Facq','Fhol','Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';
keys.epochs_spaceLR_multicomp{6}            ={'Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';
keys.epochs_choice_multicomp{6}             ={'Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';
keys.epochs_hands_multicomp{6}              ={'Facq','Fhol','Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';
keys.epochs_SxH_multicomp{6}                ={'Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';
keys.epochs_to_plot_PSTH{6}                 ={'INI','Facq','Fhol','Cue','MemE','MemL','PreS','PeriS','TIhol','Thol'}';
end

